### ISSUE TITLE
BUG Error 404 not found

### ISSUE THREAD

**Issue by Rgascoin** [anmol098/waka-readme-stats#329] opened 2022-09-17 01:59 UTC
**Describe the bug**
The github action return success but it's falling to finding my profile

**To Reproduce**
1. Launch the github action

**Expected behavior**
Having the report on my profil

**Github repository link**
https://github.com/Rgascoin/Rgascoin/actions/runs/3071729033/jobs/4962667964

**Additional context**
```
/usr/bin/docker run --name f706970e17fa8b143739e04cae636be5ad1_85d05b --label 817f70 --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_OS" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_LOCALE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_IGNORED_REPOS" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SYMBOL_VERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERI...
Traceback (most recent call last):
Username github-actions[bot]
  File "/main.py", line 557, in <module>
    repo = g.get_repo(f"{username}/{username}")
  File "/usr/local/lib/python3.9/site-packages/github/MainClass.py", line 345, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line [31](https://github.com/Rgascoin/Rgascoin/actions/runs/3071729033/jobs/4962667964#step:3:32)5, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line [34](https://github.com/Rgascoin/Rgascoin/actions/runs/3071729033/jobs/4962667964#step:3:35)0, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
Exception Occurred 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

**Comment by Rgascoin** [comment] 2022-09-17 02:03
Btw I have no problem with this one: https://github.com/athul/waka-readme
But I prefer you design

**Comment by fbuireu** [comment] 2022-10-05 13:33
Any updates on this?

**Comment by huamurui** [comment] 2022-10-31 06:31
I meet the same error. And I notice that in your repository's workflow file there is   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}.

The GITHUB_TOKEN is generated by the github-actions[bot]. 

> Username github-actions[bot]
>   File "/main.py", line 557, in <module>
>     repo = g.get_repo(f"{username}/{username}")

and here, the username also become "github-actions[bot]". so...I'm wondering if the TOKEN has to be generated by your hands and only in this way the application can get the right username.

I haven't tried yet, but I guess it may because of this。

**Comment by huamurui** [comment] 2022-10-31 10:58
I just made it worked by giving user generated TOKEN, you may need the link and information below if you want to fix it in this way.

https://github.com/anmol098/waka-readme-stats/issues/86

Choose classic to generate the TOKEN and select the workflow and user.
![图片](https://user-images.githubusercontent.com/60086749/198992608-8553a9c2-cdb5-40a2-b640-56085701aaaa.png)
![图片](https://user-images.githubusercontent.com/60086749/198992749-989f8707-9f9d-42ed-a921-5fd35c80ba45.png)

**Comment by aravindvnair99** [comment] 2022-12-05 03:44
Closing as per above. Feel free to get back if the issue is still there.

**Closed by aravindvnair99** 2022-12-05 03:44 UTC
Labels: bug
