### ISSUE TITLE
FEAT

### ISSUE THREAD

**Issue by Yeikzy** [anmol098/waka-readme-stats#286] opened 2022-05-13 17:19 UTC
Hi i went to know, how i can delete this ? (Code Time)
Thanks for you reply.

![Media](https://cdn.upload.systems/uploads/rM2TMAn8.png)

**Comment by siyual-park** [comment] 2022-05-16 00:52
This is a related issue #248

**Comment by aravindvnair99** [comment] 2022-05-16 02:46
Duplicate of #248

**Closed by aravindvnair99** 2022-05-16 02:46 UTC
Labels: Brainstorming
