### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by leroywagner** [anmol098/waka-readme-stats#335] opened 2022-10-15 06:20 UTC
```
Run anmol098/waka-readme-stats@master
/usr/bin/docker run --name d558[1](https://github.com/leroywagner/leroywagner/actions/runs/3254662014/jobs/5343168375#step:3:1)f87c7a6e722c45f3b7616432fa2146d2_167495 --label 8d5581 --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_LOCALE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_IGNORED_REPOS" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_SYMBOL_VERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/leroywagner/leroywagner":"/github/workspace" 8d5581:f87c7a6e722c45f3b7616432fa2146d2
Traceback (most recent call last):
  File "/main.py", line 550, in <module>
    user_data = run_query(userInfoQuery)  # Execute the query
  File "/main.py", line 176, in run_query
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
Exception: Query failed to run by returning code of 401. 
{
    viewer {
      login
      email
      id
    }
  }

Exception Occurred Query failed to run by returning code of [40](https://github.com/leroywagner/leroywagner/actions/runs/3254662014/jobs/5343168375#step:3:41)1. 
{
    viewer {
      login
      email
      id
    }
  }
```

**Comment by lorainemg** [comment] 2022-12-04 22:19
I had this issue. Looking at #86 helped me, it was an error with the GitHub token. I used Github's new Fine-grained personal access tokens.

**Comment by aravindvnair99** [comment] 2022-12-05 03:45
Closing as per above. Feel free to get back if the issue is still there.

**Closed by aravindvnair99** 2022-12-05 03:45 UTC
Labels: bug
